Unset DELETE method on Windows
ignitionrobotics/ign-fuel-tools pull request #161
Opened 2021-01-14 13:57 UTC by j-rivero

Delete is a reserved word on Windows. This PR runs the workaround of unset it so the [ResultType class can compile](https://github.com/ignitionrobotics/ign-fuel-tools/blob/ign-fuel-tools5/include/ignition/fuel_tools/Result.hh#L47-L48). To real fix the problem I think that we need to plan a migration from using the reserved word to another (REMOVE or something like that)

2021-01-14 18:38 UTC, chapulina commented
How about renaming it already? Maybe `DEL`? We could have both `DEL` and `DELETE` on v6 and remove `DELETE` on v7.

2021-01-25 18:24 UTC, nkoenig approved these changes

2021-01-25 21:37 UTC, chapulina requested changes
DCO needs to be signed and codecheck fixed. Renaming `DELETE` doesn't need to be addressed on this PR.

2021-01-25 21:37 UTC, chapulina commented on include/ignition/fuel_tools/RestClient.hh
> +// TODO: rename the DELETE method which is a reserved word in Windows
codecheck is failing:

```
  /github/workspace/include/ignition/fuel_tools/RestClient.hh:32:  Missing username in TODO; it should look like "// TODO(my_username): Stuff."  [readability/todo] [2]
  /github/workspace/include/ignition/fuel_tools/Result.hh:31:  Missing username in TODO; it should look like "// TODO(my_username): Stuff."  [readability/todo] [2]
```

2021-01-27 03:23 UTC, chapulina approved these changes

2021-01-27 03:23 UTC, merged